basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('billing/', include('billing.urls', namespace='billing')),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('index', views.index, name='index'),
    path('photo', views.photo, name='photo'),
    path('faq/', views.faq, name='faq'),
    path('contact/', views.contact, name='contact'),
    path('', views.product_all, name='product_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
    path('shop/<slug:risk_slug>/', views.risk_list, name='risk_list'),
]

store/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.db.models import F

TAG_CHOICES = (
    ('None','None'),
    ('On Offer', 'On Offer'),
    ('Fast Selling','Fast Selling'),
    ('New','New'),
)


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)

class Risk(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'risks'

    def get_absolute_url(self):
        return reverse('store:risk_list', args=[self.slug])

    def __str__(self):
        return self.name

class Watering(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'waterings'

    def get_absolute_url(self):
        return reverse('store:watering_list', args=[self.slug])

    def __str__(self):
        return self.name

class maintenance(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'maintenances'

    def get_absolute_url(self):
        return reverse('store:maintenance_list', args=[self.slug])

    def __str__(self):
        return self.name

class Sun(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'suns'

    def get_absolute_url(self):
        return reverse('store:sun_list', args=[self.slug])

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name

class Product(models.Model):
    pid=models.IntegerField(null=False)
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE,default=7)
    risk = models.ForeignKey(Risk, related_name='product', on_delete=models.CASCADE,default=1)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator',default=1)
    title = models.CharField(max_length=255)
    Nickname=models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.png')
    slug = models.SlugField(max_length=255)
    size=models.CharField(max_length=255, default="2-3")
    price = models.IntegerField(default=0)
    disprice = models.IntegerField(default=0)
    orgprice = models.IntegerField(default=0)
    in_stock = models.BooleanField(default=True)
    indoor = models.BooleanField(default=False)
    mother = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    sun = models.ForeignKey(Sun, related_name='product', on_delete=models.CASCADE,default=1)
    Watering = models.ForeignKey(Watering, related_name='product', on_delete=models.CASCADE,default=1)
    products = ProductManager()
    maintenance = models.ForeignKey(maintenance, related_name='product', on_delete=models.CASCADE,default=1)
    tag = models.CharField(max_length=20, choices=TAG_CHOICES, default='None')


    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

basket/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render

from store.models import Product

from .basket import Basket

def basket_delete_all(request):
    basket = Basket(request)
    print(type(basket))
    basket.clear()
    basketqty = basket.__len__()
    baskettotal = basket.get_total_price()
    response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
    return response

def basket_summary(request):
    basket = Basket(request)
    print("1")
    print(basket)
    if request.method == 'POST':
        if(request.POST["button1"]=="Add to cart"):
            print("added")
        elif(request.POST["button1"]=="clear"):
            basket_delete_all(request)

    return render(request, 'store/basket/summary.html', {'basket': basket})

def basket_add(request):
    print("2")
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        print(request.POST.get('productqty'))
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        print(product_id)
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, qty=product_qty)

        basketqty = basket.__len__()
        response = JsonResponse({'qty': basketqty})
        return response


def basket_delete(request):
    print("3")
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)
        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response

def basket_update(request):
    print("4")
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id, qty=product_qty)

        basketqty = basket.get_total()
        print(basketqty)
        baskettotal = basket.get_total_price()
        print(baskettotal)
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response
    

store/views.py
from django.shortcuts import get_object_or_404, render
from .models import Category, Product,Risk

states=["All States-H","Tamil Nadu-H","Andhra Pradesh-H","Assam-M","Bihar-L","Chhattisgarh-L","Goa-M","Gujarat-L","Haryana-M","Himachal Pradesh-L","Jharkhand-L","Karnataka-H","Kerala-H","Madhya Pradesh-L","Maharashtra-M","Meghalaya-L","Odisha-L","Punjab-M","Rajasthan-L","Telangana-M","Uttarakhand-L","Uttar Pradesh-L","West Bengal-M","Chandigarh-L","Delhi-H","Dadra, Nagar Haveli,Daman & Diu-L","Puducherry-H"]
stateName=[]
stateID=[]
for i in states:
    stateName.append(i.split('-')[0])
    stateID.append(i.split('-')[1])
state=zip(states,stateName)

def product_all(request):
    products = Product.products
    typeName="All Collection"
    if request.method=='POST':
        #Risk
        try:
            if(request.POST["btn"]=="low"):
                products=Product.products.filter(risk=1)
                typeName="Low Risk Plants"
            elif(request.POST["btn"]=="moderate"):
                products=Product.products.filter(risk=2)
                typeName="Moderate Risk Plants"
            elif(request.POST["btn"]=="high"):
                products=Product.products.filter(risk=3)
                typeName="High Risk Plants"
            elif(request.POST["btn"]=="all"):
                products = Product.products.all()
                typeName="All Collection"
            elif(request.POST["btn"]=="mlow"):
                products=Product.products.filter(maintenance=1)
                typeName="Low Maintenance Plants"
            elif(request.POST["btn"]=="mmoderate"):
                products=Product.products.filter(maintenance=2)
                typeName="Moderate Maintenance Plants"
            elif(request.POST["btn"]=="mhigh"):
                products=Product.products.filter(maintenance=3)
                typeName="High Maintenance Plants"
            elif(request.POST["btn"]=="offer"):
                products=Product.products.filter(tag="On Offer")
                typeName="On Offer"
            elif(request.POST["btn"]=="new"):
                products=Product.products.filter(tag="New")
                typeName="New"
            elif(request.POST["btn"]=="fast"):
                products=Product.products.filter(tag="Fast Selling")
                typeName="Fast Sellingr"
        except:
            pass
        #Category
        try:
            if(request.POST["cat"]=="1"):
                products=products.filter(category=1)
                typeName="Sedum /Ground Cover"
            elif(request.POST["cat"]=="2"):
                products=products.filter(category=2)
                typeName="Cactus"
            elif(request.POST["cat"]=="3"):
                products=products.filter(category=3)
                typeName="Hanging"
            elif(request.POST["cat"]=="4"):
                products=products.filter(category=4)
                typeName="Aloe"
            elif(request.POST["cat"]=="5"):
                products=products.filter(category=5)
                typeName="Haworthia"
            elif(request.POST["cat"]=="6"):
                products=products.filter(category=6)
                typeName="Other Plants"
            elif(request.POST["cat"]=="7"):
                products=products.filter(category=7)
                typeName="Succulents"
            elif(request.POST["cat"]=="8"):
                products=products.filter(category=8)
                typeName="Jade"
            elif(request.POST["cat"]=="9"):
                products=products.filter(indoor=True)
                typeName="Indoor"
            elif(request.POST["cat"]=="10"):
                products=products.filter(mother=True)
                typeName="Mother Plant"
        except:
            pass
        try:
            val=(request.POST["state"])[-1]
            typeName=(request.POST["state"][:-2])
            if(val=="L"):
                products=Product.products.filter(risk=1)
            elif(val=="M"):
                products=Product.products.exclude(risk=3)
            elif(val=="H"):
                products=Product.products.all()
        except:
            pass
        try:
            val=(request.POST["flt"])
            if(val=="wlow"):
                products=Product.products.filter(Watering=1)
            elif(val=="wnormal"):
                products=Product.products.filter(Watering=2)
            elif(val=="whigh"):
                products=Product.products.filter(Watering=3)
            if(val=="slow"):
                products=Product.products.filter(sun=1)
            elif(val=="snormal"):
                products=Product.products.filter(sun=2)
            elif(val=="shigh"):
                products=Product.products.filter(sun=3)
        except:
            pass
    products=products.order_by('pid')
    state=zip(states,stateName)
    if request.method=='POST':
        #Sort
        try:
            if(request.POST["sort"]=="new"):
                products=products.reverse()
            elif(request.POST["sort"]=="l-h"):
                products=products.order_by('price')
            elif(request.POST["sort"]=="h-l"):
                products=products.order_by('price').reverse()
        except:
            pass
    return render(request, 'store/home.html', {'products': products,'typeName':typeName,'state':state})

def risk_list(request,risk_slug=None):
    risk = get_object_or_404(Risk, slug=risk_slug)
    products = Product.objects.filter(risk=risk)
    return render(request, 'store/products/risk.html', {'risk': risk, 'products': products})

def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/single.html', {'product': product})

def index(request):
    state=zip(states,stateName)
    return render(request, 'store/index.html',{'state':state})

def contact(request):
    return render(request, 'store/contact.html')

def faq(request):
    return render(request, 'store/faq.html')

def photo(request):
    products = Product.products
    for e in Product.objects.all():
        print(e.title)
    products=products.order_by('pid')
    state=zip(states,stateName)
    return render(request, 'store/photo.html', {'products': products})

templates/store/basket/summary.html
{% extends "../base.html" %}
{% load mathfilters %}
{% load static %}
{% block title %}Cart Summary{% endblock %}
{% block import %}

{% endblock %}
{% block content %}


<main class="pt-5 mt-3">
  <div class="container">
    <a id="cart"></a>
    <div class="mb-1 text-center">
      <div class="btn-group pb-0">
        <a type="button" class="btn btn-secondary btn-block" href="/"><strong>Catalogue (click here)</strong></a>
      </div>
  </div>

    <marquee behavior="scroll" direction="left" style="background-color: rgba(255, 255, 0, 0.589);">After Adding required plants to cart please click <b>Place order</b>.</marquee>
    {% if basket|length < 5 %}
    <div class="alert alert-primary text-center py-1 mb-1" role="alert">
      Please Add Atleast <strong>5</strong> items to cart    
    </div>
    {% endif %}

    {% if basket.get_total_price >= 700 %}
    <div class="alert alert-primary text-center py-1 mb-1" role="alert">
      One Complementary plant will be added to cart since you ordered for an amount of more than 700
    </div>
    {% else %}
    <div class="alert alert-primary text-center py-1 mb-1" role="alert">
      Purchase for more than 700 and get a free gift from us.
    </div>
    {% endif %}
    <div class="h4 p-0 m-0 mb-1 pb-1 bg-success text-center text-white">Selected Plants</div>
    {% for item in basket %}
    {% with product=item.product %}
    <div data-index="{{product.id}}" class="row mb-1 border product-item mx-0">
      <div class="col-md-0 col-lg-10 ps-md-3 ps-lg-10 px-0">
        <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
          <h1 class="h6 m-0 text-center">{{product.pid}}. {{ product.title }} - <span class="h6 fw-bold">{{ product.price }}x{{item.qty}} = &#8377;{{item.qty|mul:product.price}}</span></h1>
        </a>
        
              <table class="table table-hover p-0 m-0">
                <tbody>
                <tr>
                  <td class="p-0 text-center">
                    <img
                    class="img-fluid
                    alt="Responsive image"
                    src="{{ product.image.url }}"
                    width="50px"
                  />
                  </td>
                  <td class="p-0 text-center">
                    <button type="button"
                    data-index="{{product.id}}"
                    class="btn btn-outline-secondary btn-sm p-1 mt-2"
                    data-bs-toggle="modal"
                    data-bs-target="#staticBackdrop{{product.id}}" >
                    Update
                  </button>
                  <!--Modal-->
                  <div
                  class="modal fade"
                  id="staticBackdrop{{product.id}}" data-bs-backdrop="static"
                  tabindex="-1"
                  aria-labelledby="exampleModalLabel"
                  aria-hidden="true"
                >
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">
                          Update {{ product.title }}
                        </h5>
                      </div>
                      <p class="card-text">
                        <a
                          class="text-dark text-decoration-none"
                          href="{{ product.get_absolute_url }}"
                          >{{ product.title }}</a
                        >
                      </p>
                      <div class="modal-body pb-0 mb-0">
                        <div class="text-center">
                          <label for="select">Change Qty: </label>
                          <select id="select{{product.id}}">
                            <option selected>
                            {{item.qty}}
                            </option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                            <option value="11">11</option>
                            <option value="12">12</option>
                            <option value="13">13</option>
                            <option value="14">14</option>
                            <option value="15">15</option>
                            <option value="16">16</option>
                            <option value="17">17</option>
                            <option value="18">18</option>
                            <option value="19">19</option>
                            <option value="20">20</option>
                          </select>

                        </div>
                      </div>
                      <div class="modal-footer">
                        <button type="button" id="update-button" data-index="{{product.id}}"
                        class="btn btn-outline-secondary btn-sm update-button">
                        Update Value
                        </button>
                      </div>
                      </div>
                    </div>
                  </div>
                  </td>
                  <td class="p-0 text-center">
                    <button type="submit" id="delete-button" data-index="{{product.id}}"
                      class="btn btn-outline-danger btn-sm delete-button p-1 mt-2">
                      Delete
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
      </div>
    </div>
    {% endwith %}
    {% endfor %}
    <div class="col-12 text-end">
      <h5 class="h6 fw-bold m-0 d-inline-flex">Total Plants:</h5>     {{basket|length}} 
    </div>
    <div class="col-12 text-end">
      <h5 class="h6 fw-bold m-0 d-inline-flex">Total: &#8377;</h5><div id="subtotal" class="h6 fw-bold d-inline-flex m-0"> {{basket.get_total_price}} 
      </div>
      {% if basket.get_total_price > 0 %}
      <small>+ delivery charges</small>
      {% endif %}  

    </div>
    <div class="alert alert-dark text-center m-0 mb-2 p-0" role="alert">
      After Adding required plants to cart please click <b>Place order</b>. 
        </div>
  </div>
  <div class="text-center">
    <div class="btn-group pb-1">
      <form action="/basket/" method="post">        
        {% csrf_token %}
          <button class="btn btn-danger" type="submit" name="button1" value="clear">Empty cart</button>
        </form>
        </div>
    <div class="btn-group pb-1">
      <a type="button" class="btn btn-secondary" target="_blank" href="https://api.whatsapp.com/send?phone=%2B917904050237&text=*Hello, i have chosen the following plants from your site*
%0a
{% for item in basket %}
   {% with product=item.product %}{{product.pid}}.{{ product.title }}-{{item.qty}}*{{product.price}}={{item.qty|mul:product.price}}/- %0a{% endwith %}
{% endfor %}
*Total Plants={{basket|length}}*%0a
*Total Price={{basket.get_total_price}}*%2Bdelivery%0a%0a
*Plant Id and qty*%0a 
{% for item in basket %}{% with product=item.product %}{{product.pid}}-{{item.qty}},{% endwith %}{% endfor %}%0a 
{% if basket.get_total_price > 700 %}
*%2BComplementary plant*
{% endif %}  
">Place Order</a>
    </div>
  </div>
  <br>
  <br>
  <br>
</main>
<script>
  // Delete Item
  $(document).on('click', '.delete-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_delete" %}',
      data: {
        productid: $(this).data('index'),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        $('.product-item[data-index="' + prodid + '"]').remove();
        document.getElementById("subtotal").innerHTML = json.subtotal;
        document.getElementById("basket-qty").innerHTML = json.qty;
        document.location.reload();
      },
      error: function (xhr, errmsg, err) {}
    });
  })

  // Update Item
  $(document).on('click', '.update-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_update" %}',
      data: {
        productid: $(this).data('index'),
        productqty: $('#select' + prodid + ' option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        document.getElementById("basket-qty").innerHTML = json.qty
        document.getElementById("subtotal").innerHTML = json.subtotal
        document.location.reload();
      },
      error: function (xhr, errmsg, err) {}
    });
  })

  var fired_button = "none";
  $("button").click(function () {});

  $(document).on("click", "button", function (e) {
    var val = this.id + "sel";
    var qua = document.getElementById(val).value;
    e.preventDefault();
    $.ajax({
      type: "POST",
      url: '{% url "basket:basket_add" %}',
      data: {
        productid: this.id,
        productqty: qua,
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
        document.getElementById("val").innerHTML = json.qty;
        document.location.reload();
      },
      error: function (xhr, errmsg, err) {},
    });
  });

  function reloadPage(){
    location.reload(true);
}
</script>

{% endblock %}